name: localhost-screenshot

on: push

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Check for changed files
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            changed:
              - 'packages/localhost-screenshot/**'

  test:
    needs: changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.changed == 'true' }}

    steps:
      - name: Print environment variables
        run: |
          echo "CWD - `pwd`"
          echo "HOME - $HOME"
          echo "GITHUB_WORKSPACE - $GITHUB_WORKSPACE"

      - name: Test action
        uses: ./packages/localhost-screenshot
        env:
          DEBUG: localhost-screenshot
        with:
          dark: true
          devices: iPhone 11, iPad, desktop
          dist: './packages/localhost-screenshot/__tests__'

      - name: Screenshot output
        run: ls -lha /home/runner/work/_temp/_github_home/

      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: /home/runner/work/_temp/_github_home/**.png
          retention-days: 1
